//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class DialogueUI
{
    [SerializeField]
    private UIDocument _document;
    public VisualElement LeftCharacter { get; private set; }

    public VisualElement RightCharacter { get; private set; }

    public VisualElement LeftCharacterContainer { get; private set; }

    public VisualElement RightCharacterContainer { get; private set; }

    public Label SpeakerName { get; private set; }

    public Label DialogueText { get; private set; }

    public Button Option1 { get; private set; }

    public Button Option2 { get; private set; }

    public Button Option3 { get; private set; }

    public VisualElement TextContainer { get; private set; }

    public VisualElement OptionsContainer { get; private set; }

    public VisualElement CharactersContainer { get; private set; }

    public VisualElement DialogueBoxContainer { get; private set; }

    public VisualElement DialogueContainer { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        LeftCharacter = Root?.Q<VisualElement>("left-character");
        RightCharacter = Root?.Q<VisualElement>("right-character");
        LeftCharacterContainer = Root?.Q<VisualElement>("left-character-container");
        RightCharacterContainer = Root?.Q<VisualElement>("right-character-container");
        SpeakerName = Root?.Q<Label>("speaker-name");
        DialogueText = Root?.Q<Label>("dialogue-text");
        Option1 = Root?.Q<Button>("option-1");
        Option2 = Root?.Q<Button>("option-2");
        Option3 = Root?.Q<Button>("option-3");
        TextContainer = Root?.Q<VisualElement>("text-container");
        OptionsContainer = Root?.Q<VisualElement>("options-container");
        CharactersContainer = Root?.Q<VisualElement>("characters-container");
        DialogueBoxContainer = Root?.Q<VisualElement>("dialogue-box-container");
        DialogueContainer = Root?.Q<VisualElement>("dialogue-container");
    }
}