//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class GameDialogueComponent
{
    [SerializeField]
    private UIDocument _document;
    public VisualElement LeftCharacter { get; private set; }

    public VisualElement RightCharacter { get; private set; }

    public VisualElement LeftCharacterContainer { get; private set; }

    public VisualElement RightCharacterContainer { get; private set; }

    public Label SubtitleLabel { get; private set; }

    public Button ContinueButton { get; private set; }

    public Button ResponseButton0 { get; private set; }

    public Button ResponseButton1 { get; private set; }

    public Button ResponseButton2 { get; private set; }

    public VisualElement SubtitlePanel { get; private set; }

    public VisualElement ResponsePanel { get; private set; }

    public Button SettingsButton { get; private set; }

    public VisualElement CharactersContainer { get; private set; }

    public VisualElement DialoguePanel { get; private set; }

    public VisualElement SettingsBg { get; private set; }

    public VisualElement Container { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        LeftCharacter = Root?.Q<VisualElement>("left-character");
        RightCharacter = Root?.Q<VisualElement>("right-character");
        LeftCharacterContainer = Root?.Q<VisualElement>("left-character-container");
        RightCharacterContainer = Root?.Q<VisualElement>("right-character-container");
        SubtitleLabel = Root?.Q<Label>("SubtitleLabel");
        ContinueButton = Root?.Q<Button>("ContinueButton");
        ResponseButton0 = Root?.Q<Button>("ResponseButton0");
        ResponseButton1 = Root?.Q<Button>("ResponseButton1");
        ResponseButton2 = Root?.Q<Button>("ResponseButton2");
        SubtitlePanel = Root?.Q<VisualElement>("SubtitlePanel");
        ResponsePanel = Root?.Q<VisualElement>("ResponsePanel");
        SettingsButton = Root?.Q<Button>("SettingsButton");
        CharactersContainer = Root?.Q<VisualElement>("characters-container");
        DialoguePanel = Root?.Q<VisualElement>("DialoguePanel");
        SettingsBg = Root?.Q<VisualElement>("settings-bg");
        Container = Root?.Q<VisualElement>("Container");
    }
}