//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class MainMenuComponent
{
    [SerializeField]
    private UIDocument _document;
    public VisualElement MountainParallaxDark { get; private set; }

    public Button PlayButton { get; private set; }

    public Button SettingsButton { get; private set; }

    public Button QuitButton { get; private set; }

    public VisualElement PlayBg { get; private set; }

    public VisualElement SettingsBg { get; private set; }

    public VisualElement QuitBg { get; private set; }

    public VisualElement MountainParallax { get; private set; }

    public Label GameTitle { get; private set; }

    public VisualElement ButtonContainer { get; private set; }

    public VisualElement OriseiParallax { get; private set; }

    public VisualElement MainMenuContainer { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        MountainParallaxDark = Root?.Q<VisualElement>("mountain-parallax-dark");
        PlayButton = Root?.Q<Button>("play-button");
        SettingsButton = Root?.Q<Button>("settings-button");
        QuitButton = Root?.Q<Button>("quit-button");
        PlayBg = Root?.Q<VisualElement>("play-bg");
        SettingsBg = Root?.Q<VisualElement>("settings-bg");
        QuitBg = Root?.Q<VisualElement>("quit-bg");
        MountainParallax = Root?.Q<VisualElement>("mountain-parallax");
        GameTitle = Root?.Q<Label>("game-title");
        ButtonContainer = Root?.Q<VisualElement>("button-container");
        OriseiParallax = Root?.Q<VisualElement>("orisei-parallax");
        MainMenuContainer = Root?.Q<VisualElement>("main-menu-container");
    }
}